# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CoolifyCli < Formula
  desc "CLI tool for interacting with the Coolify API"
  homepage "https://coolify.io"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coollabsio/coolify-cli/releases/download/v1.7.0/coolify-cli_1.7.0_darwin_amd64.tar.gz"
      sha256 "1d42fa69258e21446224b2882a76813e65d2648e2c96bbf3f7f14866666e83fd"

      define_method(:install) do
        bin.install "coolify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coollabsio/coolify-cli/releases/download/v1.7.0/coolify-cli_1.7.0_darwin_arm64.tar.gz"
      sha256 "edf19b9863f8afda7dc56752878b3c214f017302137fda552b9d4c0ef71c0c64"

      define_method(:install) do
        bin.install "coolify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coollabsio/coolify-cli/releases/download/v1.7.0/coolify-cli_1.7.0_linux_amd64.tar.gz"
      sha256 "b64ea855f43984ec12b01b5b36dda833008b40d59e030834aa7a112d285d5323"
      define_method(:install) do
        bin.install "coolify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coollabsio/coolify-cli/releases/download/v1.7.0/coolify-cli_1.7.0_linux_arm64.tar.gz"
      sha256 "285236f2cdca0f2672548875a3799e4c695089160f36405716e5c1c24448597a"
      define_method(:install) do
        bin.install "coolify"
      end
    end
  end

  test do
    system "#{bin}/coolify", "version"
  end
end
